### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by phillipsl0**
figured we should merge into master, so can everyone please look at this and if there are no issues you find then approve (but don't merge unless you're the last reviewer, please!)

### CODE REVIEW

**Review by childv — DISMISSED** [review]
Checked out the app on iOS - looks good!

**Review by Martination — DISMISSED** [review]
Looks as good as the previous master on Android

**Review by childv — DISMISSED** [review]

**Comment by andrew-woosnam** [comment]
Some things are still loading pretty slowly and @childv found a bug in the buildings list, but nothing too serious -- looks nice and stable to me!

**Review by andrew-woosnam — APPROVED** [review]
Stable! Let's fix the double-tap button bug soon though

**Pull request merged**
